In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print("After adding 2:", arr + 2)
print("After multiplying by 3:", arr * 3)
print("After dividing by 2:", arr / 2)

After adding 2: [3 4 5 6 7]
After multiplying by 3: [ 3  6  9 12 15]
After dividing by 2: [0.5 1.  1.5 2.  2.5]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
print(np.flip(arr))

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

freq = {}
for i in x:
    freq[i] = freq.get(i, 0) + 1

maxfreq = max(freq.values())

for i in freq:
    if freq[i] == maxfreq:
        indices = np.where(x == i)[0]
        print("Value:", i)
        print("Frequency:", maxfreq)
        print("Indices:", indices)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

freq = {}
for i in y:
    freq[i] = freq.get(i, 0) + 1

maxfreq = max(freq.values())

for i in freq:
    if freq[i] == maxfreq:
        indices = np.where(y == i)[0]
        print("Value:", i)
        print("Frequency:", maxfreq)
        print("Indices:", indices)

[5 4 6 3 2 1]
Value: 1
Frequency: 5
Indices: [0 5 7 8 9]
Value: 1
Frequency: 3
Indices: [0 1 2]
Value: 3
Frequency: 3
Indices: [4 8 9]


In [4]:
import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(arr[0][1])
print(arr[2][0])

20
70


In [5]:
import numpy as np

SahilSharma = np.linspace(10, 100, 25)

print(SahilSharma)
print(SahilSharma.ndim)
print(SahilSharma.shape)
print(SahilSharma.size)
print(SahilSharma.dtype)
print(SahilSharma.nbytes)

reshapedarr = SahilSharma.reshape(25, 1)
print(reshapedarr)

print(SahilSharma.T)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
1
(25,)
25
float64
200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [6]:
import numpy as np

ucs420_SahilSharma = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print(np.mean(ucs420_SahilSharma))
print(np.median(ucs420_SahilSharma))
print(np.max(ucs420_SahilSharma))
print(np.min(ucs420_SahilSharma))
print(np.unique(ucs420_SahilSharma))

reshaped_ucs420_SahilSharma = ucs420_SahilSharma.reshape(4, 3)
print(reshaped_ucs420_SahilSharma)

resized_ucs420_SahilSharma = np.resize(ucs420_SahilSharma, (2, 3))
print(resized_ucs420_SahilSharma)

43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
